### ISSUE TITLE
Calling CamembertTokenizer.from_pretrained() with the path to a single file or url is deprecated

### ISSUE THREAD

**Issue by harshrathod50** [achieveordie/IsItCorrect#3]
I get this error when I execute "app.py" script.

### conda
```
(base) [root@vps47654603 is-it-correct]# python3.8 app.py
Calling CamembertTokenizer.from_pretrained() with the path to a single file or url is deprecated
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    model = load_model(save_model_location)
  File "app.py", line 22, in load_model
    model.load_state_dict(torch.load(save_model_location))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

### pip3
```
[root@vps47654603 is-it-correct]# python3.8 app.py
Calling CamembertTokenizer.from_pretrained() with the path to a single file or url is deprecated
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    model = load_model(save_model_location)
  File "app.py", line 22, in load_model
    model.load_state_dict(torch.load(save_model_location))
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

### Other
There is a similar [issue](https://github.com/huggingface/transformers/issues/2667). It might be related to ours.

**Comment by achieveordie** [comment]
@harshrathod50 `Calling CamembertTokenizer.from_pretrained() with the path to a single file or url is deprecated` is a warning and not the source of the error. One can avoid getting this error by simply avoiding passing the exact `sentencepiece.bpe.model` into `.from_pretrained()`.

Code:
```
tokenizer_location = "./"
tokenizer = CamembertTokenizer.from_pretrained(tokenizer_location) 
```

Regarding the error, it seems to me that it is due to [this ](https://github.com/YBIGTA/pytorch-hair-segmentation/issues/38#issuecomment-510380364)problem. git clone would avoid getting `model_1.pth` in correct format since that file is well over 400 MB. The proposed solution is:

> when you git clone the repo, the file in model are not the correct one, there are too big to be download by git, there are replace by text file. You can either download them manually, on the website github just click on download, either using git-lfs who is "An open source Git extension for versioning large files" who manage this kind of file in this project.

Let me know if it works or not.

**Comment by harshrathod50** [comment]
Yes, LFS was the problem. This error has been resolved now.
